imports:
    - { resource: 'services/rules.yml' }
    - { resource: 'services/product-quantity-price-rules.yml' }
    - { resource: 'services/actions.yml' }
    - { resource: 'services/calculator.yml' }

services:
    CoreShop\Bundle\ProductQuantityPriceRulesBundle\Templating\Helper\ProductQuantityPriceRuleRangesHelperInterface: '@CoreShop\Bundle\ProductQuantityPriceRulesBundle\Templating\Helper\ProductQuantityPriceRuleRangesHelper'
    CoreShop\Bundle\ProductQuantityPriceRulesBundle\Templating\Helper\ProductQuantityPriceRuleRangesHelper:
        arguments:
            - '@CoreShop\Component\ProductQuantityPriceRules\Detector\QuantityReferenceDetectorInterface'
        tags:
            - { name: templating.helper, alias: coreshop_product_quantity_price_rule_ranges }

    CoreShop\Bundle\ProductQuantityPriceRulesBundle\Twig\ProductQuantityPriceRuleRangesExtension:
        public: false
        arguments:
            - '@CoreShop\Bundle\ProductQuantityPriceRulesBundle\Templating\Helper\ProductQuantityPriceRuleRangesHelperInterface'
        tags:
            - { name: twig.extension }
