services:
    coreshop.registry.product_quantity_price_rules.actions:
        class: CoreShop\Component\Registry\ServiceRegistry
        arguments:
            - CoreShop\Component\ProductQuantityPriceRules\Rule\Action\ProductQuantityPriceRuleActionInterface
            - product-quantity-price-rules-actions

    coreshop.product_quantity_price_rules.action.percentage_decrease:
        class: CoreShop\Component\ProductQuantityPriceRules\Rule\Action\PercentageDecreaseAction
        arguments:
            - '%coreshop.currency.decimal_factor%'
        tags:
            - { name: coreshop.product_quantity_price_rules.action, type: percentage_decrease }

    coreshop.product_quantity_price_rules.action.percentage_increase:
        class: CoreShop\Component\ProductQuantityPriceRules\Rule\Action\PercentageIncreaseAction
        arguments:
            - '%coreshop.currency.decimal_factor%'
        tags:
            - { name: coreshop.product_quantity_price_rules.action, type: percentage_increase }

