services:
    coreshop.registry.product_quantity_price_rules.calculators:
        class: CoreShop\Component\Registry\ServiceRegistry
        arguments:
            - CoreShop\Component\ProductQuantityPriceRules\Calculator\CalculatorInterface
            - product-quantity-price-rules-calculators

    CoreShop\Component\ProductQuantityPriceRules\Calculator\VolumeCalculator:
        arguments:
            - '@coreshop.registry.product_quantity_price_rules.actions'
        tags:
            - { name: coreshop.product_quantity_price_rules.calculator, type: volume }
